### ISSUE TITLE
Welcome page

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash.github.io#1]
We need to create an index page with links to the readmes

As it is https://wrye-bash.github.io gives 404

**Comment by Metallicow** [comment]
A link to the actual web rendered page in a readme.md on the github front page is a nice shortcut also for website.io repos that some people do.

**Comment by Utumno** [comment]
@Sharlikran - seeing you already did this, yours !

Granted you write access - don't push to master but you are free to push to branches here ;)

What a shame we can't preview things that are not on master - duh

**Comment by Utumno** [comment]
Last two commits close this - of course editing the welcome page @ https://wrye-bash.github.io/ is, err, welcome
